services:
  giveat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '8088:8088'
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    env_file:
      - .env
    networks:
    - giveat

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d giveat_dev" ]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres
    container_name: postgres_GivEat
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - giveat
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"

    networks:
      - giveat
    restart: unless-stopped
    depends_on:
      - postgres


  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - giveat
    restart: unless-stopped


volumes:
  db:

networks:
  giveat:
    driver: bridge