spring:

  datasource:

    url: ${DB_URL_PROD}
    password: ${DB_USER_PROD}
    username: ${DB_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    jdbc:
      dialect: postgresql

  security:
    jwt:
      expiration: 900000
      refresh-token:
        expiration: 604800000

  mail:
    username: ${SMTP_CLIENT_PROD}
    password: ${SMTP_PW_PROD}

