spring:

  jpa:
    hibernate:
      ddl-auto: validate

  security:
    jwt:
      expiration: 900000
      refresh-token:
        expiration: 604800000

  mail:
    username: ${SMTP_CLIENT_PROD}
    password: ${SMTP_PW_PROD}
