spring:

  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USER_DEV}
    password: ${DB_PASSWORD_DEV}

  jpa:
    hibernate:
      ddl-auto: update

  security:
    jwt:
      expiration: 1 #d
      refresh-token:
        expiration: 15 #d
  mail:
    username: ${SMTP_CLIENT_DEV}
    password: ${SMTP_PW_DEV}