spring:

  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USER_DEV}
    password: ${DB_PASSWORD_DEV}

  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    jwt:
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  mail:
    username: ${SMTP_CLIENT_DEV}
    password: ${SMTP_PW_DEV}